name: CI - End-to-End

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "src/**"
      - "postgres/**"
      - ".github/workflows/ci-e2e.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "src/**"
      - "postgres/**"
      - ".github/workflows/ci-e2e.yml"
  workflow_dispatch:

jobs:
  ci-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      db:
        image: postgres:17.4-bookworm
        env:
          TZ: Asia/Tokyo
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: __ENTER_POSTGRES_PASSWORD_HERE__
          POSTGRES_DB: todos_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      # Setup Database
      - name: Setup Database
        run: |
          PGPASSWORD=__ENTER_POSTGRES_PASSWORD_HERE__ psql -h localhost -p 5432 -U postgres -d todos_db -f ./postgres/init/01_create_todos.sql
          PGPASSWORD=__ENTER_POSTGRES_PASSWORD_HERE__ psql -h localhost -p 5432 -U postgres -d todos_db -f ./postgres/init/99_create_examples.sql

      # Setup and Run Backend API
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build Backend
        working-directory: ./src/backend
        run: ./gradlew build --no-daemon
      - name: Start Backend API Server
        working-directory: ./src/backend
        run: |
          java -jar modules/todos-api/build/libs/todos-api-0.0.1-SNAPSHOT.jar &
          echo $! > backend.pid
          # Wait for backend to be ready
          timeout 60 bash -c 'until curl -f http://localhost:8080/v1/greeting/hello; do sleep 2; done'

      # Setup and Run Frontend
      - name: Extract Node.js version from package.json
        working-directory: ./src/frontend/todos-web
        run: echo "NODE_VERSION=$(jq -r '.volta.node' package.json)" >> $GITHUB_ENV
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "./src/frontend/todos-web/package-lock.json"
      - name: Install Frontend dependencies
        working-directory: ./src/frontend/todos-web
        run: npm ci
      - name: Build Frontend
        working-directory: ./src/frontend/todos-web
        run: npm run build
      - name: Start Frontend Server
        working-directory: ./src/frontend/todos-web
        run: |
          npm run start &
          echo $! > frontend.pid
          # Wait for frontend to be ready
          timeout 60 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'

      # Cache Playwright browsers
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      # Install Playwright browsers
      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        working-directory: ./src/frontend/todos-web
        run: npx playwright install --with-deps

      # Run E2E tests
      - name: Run E2E tests
        working-directory: ./src/frontend/todos-web
        run: npm run e2e

      # Upload test results
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./src/frontend/todos-web/playwright-report/
          retention-days: 30

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./src/frontend/todos-web/test-results/
          retention-days: 30

      # Cleanup
      - name: Stop servers
        if: always()
        run: |
          if [ -f ./src/backend/backend.pid ]; then
            kill $(cat ./src/backend/backend.pid) || true
          fi
          if [ -f ./src/frontend/todos-web/frontend.pid ]; then
            kill $(cat ./src/frontend/todos-web/frontend.pid) || true
          fi
