name: CI - End-to-End (new)
on:
  push:
    branches:
      - main
      - develop
    paths:
      - "src/**"
      - "postgres/**"
      - ".github/workflows/playwright.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "src/**"
      - "postgres/**"
      - ".github/workflows/playwright.yml"
  workflow_dispatch:

jobs:
  ci-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract Node.js version from package.json
        working-directory: ./src/frontend/todos-web
        run: echo "NODE_VERSION=$(jq -r '.volta.node' package.json)" >> $GITHUB_ENV
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "./src/frontend/todos-web/package-lock.json"
      - name: Install Frontend dependencies
        working-directory: ./src/frontend/todos-web
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: ./src/frontend/todos-web
        run: npx playwright install --with-deps
      - name: Run E2E tests
        working-directory: ./src/frontend/todos-web
        run: npm run e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
